In [11]:
import numpy

In [14]:
a = numpy.array([10, 20, 30, 40])
a

array([10, 20, 30, 40])

In [15]:
type(a)

numpy.ndarray

In [22]:
matriz = numpy.array([[1, 2], [3, 4]])
matriz

array([[1, 2],
       [3, 4]])

In [23]:
print(matriz[1][1])
print(matriz[-1][-1])

4
4


In [29]:
matriz[1]

array([3, 4])

In [32]:
matriz[::,0]

array([1, 3])

In [35]:
matriz.transpose()

array([[1, 3],
       [2, 4]])

In [38]:
m1 = numpy.array([[1, 2], [3, 4]])
m2 = numpy.array([[5, 6], [7, 8]])
m1 + m2

array([[ 6,  8],
       [10, 12]])

In [40]:
m1 - m2

array([[-4, -4],
       [-4, -4]])

In [42]:
m1 * m2

array([[ 5, 12],
       [21, 32]])

In [44]:
m3 = numpy.array([1,2,3,4])
m3.sum()

10

In [47]:
m3.argmax()

3

In [48]:
m3.argmin()

0